Feature/minjung/lounge
mju-likelion/lionking pull request #18
Opened 2022-07-25 18:44 UTC by ypd06021

2022-07-25 19:24 UTC, ndaemy commented on .github/workflows/pr_check.yml
> +      actions: read
맨 끝에 new line 넣어주세요

2022-07-25 19:25 UTC, ndaemy commented on ormconfig.json
> +}
요기도 new line 이 사라졌네여

2022-07-25 19:26 UTC, ndaemy requested changes

2022-07-25 19:26 UTC, ndaemy commented on src/lounge/lounge.controller.ts
> +@Controller('api/lounge')
RESTful 하려면 lounges가 맞을터인디..?

2022-07-25 19:26 UTC, ndaemy commented
PR 이름도 바꿔주시지요

2022-07-27 15:46 UTC, Crmal reviewed
멋져요 👍

2022-07-27 15:46 UTC, Crmal commented on src/lounge/lounge.service.ts
> +    return new ResponseDto(`liontown.city/lounges/${url}`);
이 부분 생각해봤는데 이러면
{
  "data": {
      "message": "liontown.city/lounges/{url}"
      }
 }
 이렇게 나올텐데 message가 아니라 다른걸로 바꿔야 할듯???

2022-08-03 17:34 UTC, merged